#!/bin/bash

# change this regarding to your doxygen installation (here is Mac OSX)
DOXYGEN_BIN="/Applications/Doxygen.app/Contents/Resources/doxygen"

for doxy_config_file in `find . -name *.doxyfile` 
do
# generate doxygen HTML output for any config file with doxyfile extention in subdirectories
$DOXYGEN_BIN $doxy_config_file 
done 

# now generate p7 specification HTML output
`perl p7/p7spectohtml.pl p7/examples/wired.xml > p7/wired.html`